### ISSUE TITLE
Review request for subpackage

### ISSUE THREAD

**Issue by tclose** [nipype/pydra-dcm2niix#1]
Hi @satra @effigies @djarecka (anyone else interested),

Can you give this Pydra subpackage a quick look over before I release version 1.0?

**Comment by effigies** [comment]
Overall, LGTM. Re-ran to get codecov going, and it seems to work.

I'm not sure what `import_script.py` is doing. Is it still needed? If so, a bit of documentation would be useful.

Also in terms of documentation, installation instructions and example usage in the README would be good. We should probably update the template with some boilerplate that can be customized. Longer term, we might want to use the [criteria](https://joss.readthedocs.io/en/latest/review_checklist.html#documentation) that JOSS uses for review as a guide.

**Comment by tclose** [comment]
I have deleted import script (I used to to partially parse the help output of the dcm2niix command) and have added installation instructions and basic use cases to the README.

**Comment by effigies** [comment]
Cool, LGTM.

**Comment by tclose** [comment]
Cheers, thanks
