### ISSUE TITLE
File extension needs to change if compression not set

### ISSUE THREAD

**Issue by tclose** [nipype/pydra-dcm2niix#5]
What is the best way to implement this required functionality. The out_file extension needs to be '.nii' if compression is not set but '.nii.gz' if it is. Is it possible to use the out_file_template or do we need to create a custom callable?

https://github.com/nipype/pydra-dcm2niix/blob/c48a75fea41ff5e77330255bbeccebb3a11c2a7d/pydra/tasks/dcm2niix/utils.py#L282

**Comment by effigies** [comment]
I don't really know how to do this with the current setup, but I might not know everything that's been implemented...

I can think of two syntaxes:
```Python
     "output_file_template": "{out_dir}/{filename}.nii{'.gz'|compression}",
     "output_file_template": "{out_dir}/{filename}.nii{compression}",
```

In the first one, the pipe is "conditional" in the sense of `P(A|B)`. In the second, we would need to change `compression` to be `.gz` or `False` (where `False` would be evaluated to the empty string in these templates).

**Comment by tclose** [comment]
Thanks for the input @effigies. I meant to link #6 to this issue where I ended up just implementing the logic in a callable (which might make the most sense for something like this)

**Comment by tclose** [comment]
FWIW I quite like the 

```
     "output_file_template": "{out_dir}/{filename}.nii{'.gz'|compression}",
```

syntax

**Comment by djarecka** [comment]
sorry for delay, is `out_dir` an additional input? you want to provide an additional structure to the pydra output directory?

**Comment by tclose** [comment]
Yes, is an input `out_dir` that specifies where the directory the files will be written to.

It is not about providing structure to the output directory, but anticipating the naming structure that Dcm2Niix uses when converting different types of images (i.e. adding different file extensions/suffixes)

**Comment by tclose** [comment]
Closing this as this has been implemented within a `callable`
